apiVersion: apps/v1
kind: Deployment
metadata:
  name: change-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: change-app
  template:
    metadata:
      labels:
        app: change-app
    spec:
      containers:
        - name: django
          image: sbe03011/change-app
          ports:
            - containerPort: 8000
