resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: sbe03011/django-app
    newName: sbe03011/django-app
    newTag: v1.0.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
