apiVersion: v1
kind: Service
metadata:
  name: change-service
  labels:
    app: change-app
spec:
  type: ClusterIP
  selector:
    app: change-app
  ports:
    - name: http
      protocol: TCP
      port: 80          
      targetPort: 8000 
